package com.johnsnowlabs

import com.johnsnowlabs.nlp.{Annotation, Annotator}

class UpperCaseAnnotator extends Annotator {

  /**
   * takes a document and annotations and produces new annotations of this annotator's annotation type
   *
   * @param annotations Annotations that correspond to inputAnnotationCols generated by previous annotators if any
   * @return any number of annotations processed for every input annotation. Not necessary one to one relationship
   */
  override def annotate(annotations: Seq[Annotation]): Seq[Annotation] = {
    annotations.map(annotation =>
      Annotation(annotation.annotatorType, annotation.begin, annotation.end, annotation.result.toUpperCase(),
        annotation.metadata))
  }

}
